import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/CardMeanings.module.css'
import { makeStyles } from '@material-ui/core/styles'
import TextField from '@material-ui/core/TextField'
import Button from '@material-ui/core/Button'
import Box from '@material-ui/core/Box'
import { useState } from 'react'
import background from '../public/back.jpg'
import { motion, AnimatePresence } from 'framer-motion'
import {cards} from '../cards.js'
import Card from '@material-ui/core/Card'

const useStyles = makeStyles({
  root: {
    padding: '20px',
    margin: '10px',
    backgroundColor: 'black',
    color: 'white',
  },
  flexdisplay: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  button: {

  }
})


export default function CardMeanings({  }) {
  const classes = useStyles();

  return (
    <div className={styles.container}>
      <div className={styles.overlay}></div>
      <Head>
        <title>Giotto Tarot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href="/"><Button>Back to Home</Button></Link>
        <h2> check out our api endpoints: </h2>
        <div className={styles.row} layout="true">
          <motion.div className={styles.modal}>
            <AnimatePresence>  
            <div className={styles.column}>
                <Link href="/api/cards">
                    <Button> all cards with api/cards </Button>
                </Link>
                <Link href="/api/card/1">
                    <Button> individual cards with api/cards/[id]</Button>
                </Link>
            </div>
            </AnimatePresence>
          </motion.div>
        </div>
      </main>
    </div>
  )
}
