import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/CardMeanings.module.css'
import { makeStyles } from '@material-ui/core/styles'
import TextField from '@material-ui/core/TextField'
import Button from '@material-ui/core/Button'
import Box from '@material-ui/core/Box'
import { useState } from 'react'
import background from '../public/back.jpg'
import { motion, AnimatePresence } from 'framer-motion'
import {cards} from '../cards.js'
import Card from '@material-ui/core/Card'

const useStyles = makeStyles({
  root: {
    padding: '20px',
    margin: '10px',
    backgroundColor: 'black',
    color: 'white',
  },
  flexdisplay: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  button: {

  }
})


export default function CardMeanings({  }) {
  const classes = useStyles();

  console.log(cards);
  


  return (
    <div className={styles.container}>
      <div className={styles.overlay}></div>
      <Head>
        <title>Giotto Tarot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href="/"><Button>Back to Home</Button></Link>
        <h2> Card Meanings: </h2>
        <div className={styles.row} layout="true">
          <motion.div className={styles.modal}>
            <AnimatePresence>  
            <div className={styles.row}>
            {cards.map( (card) => {
              return (
                  <Card key={card.id} className={styles.card}>
                    <Image src={'/../public/' + card.id + '.jpg' } height="400" width="300"></Image>
                  <h2>{card.title}</h2>
                  <p>{card.description}</p>
                  </Card>
                )
            })}
            </div>
            </AnimatePresence>
          </motion.div>
        </div>
      </main>
    </div>
  )
}
